In [15]:
import numpy as np

In [5]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [7]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [8]:
# Get Dimension
a.ndim

1

In [9]:
# Get Shape - will print out the number of rows and cols
b.shape

(2, 3)

In [10]:
# Get Type
a.dtype

dtype('int32')

In [11]:
# Get Size
a.itemsize

4

In [14]:
# Get Total Size - this is also equal to the size(num of elements) * itemsize
a.nbytes
# we can also specify in the array how many bytes we want to use. a = np.array([1,2,3], dtype="int16 or int32")
# we can do the same with the array b, but we'll get a different amount of bytes, because we have floats

12

# Accessing / Changing Specific Elements, Rows, Columns, etc

In [17]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [18]:
# get a specific element [r, c]
a[1, 5]

13

In [19]:
# get a specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [20]:
# get a specific column

In [21]:
a[:, 2]

array([ 3, 10])

In [23]:
# getting a little more fancy [start:end:step]
a[0, 1:6:2] # we get the first row (0), and set the start:end:step indexes for the first row

array([2, 4, 6])

In [26]:
# we can also change some of the items in our array
a[1,5] = 20 # row(1), item on index 5 was 13, and now its 20
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 20, 14]])

In [28]:
# we can also change series of items, not just one
a[:,2] = 5 # so now for every row, the items at index 2 will be changed to 5
a

array([[ 1,  2,  5,  4,  5,  6,  7],
       [ 8,  9,  5, 11, 12, 20, 14]])

In [31]:
# we can even specify the series, to be a different item for each row
a[:,2] = [1,2]
a

array([[ 1,  2,  1,  4,  5,  6,  7],
       [ 8,  9,  2, 11, 12, 20, 14]])

In [33]:
# 3-D example


In [34]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
b

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [35]:
# get specific element (work outside in)
b[0,1,1]

4

In [36]:
b[:,1,:] # for each series, and every column, get the item on index 1

array([[3, 4],
       [7, 8]])

In [42]:
# we can also asign different items to the ones we've accessed
b[:,1,:] = [[9,9],[8,8]] # we must have the exact same amount of item, otherwise we'll get error
b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

# Initializing Different Types of Arrays

In [45]:
# All 0's matrix
np.zeros(5) # we specify a shape and we get a vector of 5

array([0., 0., 0., 0., 0.])

In [46]:
np.zeros((2,3)) # 2-D

array([[0., 0., 0.],
       [0., 0., 0.]])

In [47]:
np.zeros((2,3,3)) # 3-D and so on

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [51]:
# All 1's matrix
np.ones((4,2,2), dtype='int32') #and we can even sspecify the data type, basically removed the "."

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [52]:
# Any other number
np.full((2,2), 99) # we can specify the format of the array, and the values for each item

array([[99, 99],
       [99, 99]])

In [53]:
# Any other number (full_like) - this passess in a different array that we have used before
np.full_like(a, 4) #or np.full(a.shape, 4) - practically the same

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [54]:
# We know that the array "a" was 2:7 (rows:cols), therefore we "copy-paste" that array using the full_like function, and then we
# assign a value for each value of the array "4"

In [58]:
# Random Decimal Numbers
np.random.rand(4,2,3) # here we don't pass a tuple, but rather just the shape of the matrix, therefore 4:2 (rows:cols) and even pass more dimensions

array([[[0.96030073, 0.18033677, 0.7148637 ],
        [0.8152001 , 0.46483121, 0.73466234]],

       [[0.3006656 , 0.90848646, 0.88436249],
        [0.56962915, 0.00751946, 0.54724765]],

       [[0.16333112, 0.14605053, 0.71711551],
        [0.04138543, 0.85127146, 0.02380454]],

       [[0.80989905, 0.2260274 , 0.20381891],
        [0.17907847, 0.02197832, 0.49604789]]])

In [59]:
# if we want to pass a shape directly, we can use the "random_sample()" function
np.random.random_sample(a.shape) # our array "a" was 2:7, and we pass that shape to our new array, but with random decimals

array([[0.75541063, 0.78215519, 0.02531148, 0.16727696, 0.50940593,
        0.08161884, 0.34022388],
       [0.18559332, 0.62987064, 0.19125315, 0.80336476, 0.62051639,
        0.07048185, 0.16126327]])

In [63]:
# Random Integer Values
np.random.randint(7, size=(3,3)) # the "7" will assign random values from 0 to 7 to each item, and then we have the size, 3:3 (rows:cols)
# we can even specify different parameters, just like with "Lists", start:end:step
# Remember, the last number is allways exclusive, so we have to increase it by 1

array([[2, 4, 5],
       [6, 1, 2],
       [1, 4, 3]])

In [67]:
# Identyt Matrix - a matrix that is a square by nature, and the values we pass are possitioned diagonally
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [70]:
arr = np.array([[1,2,3]]) # we can create an array, and tell it to repeat a sequence of numbers for each row by using the repeat() function.
r1 = np.repeat(arr,3, axis=0) # here we use the repeat() function and after the "arr (our array)", we tell it to repeat the sequency for a total of 3 rows
r1

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [110]:
arr2 = np.full((5,5), 1)
arr2

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [115]:
arr2[1:4,1:4] = 0
arr2[2:3,2:3] = 9
arr2

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 9, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

In [125]:
arr3 = np.full((5,5), 1)
arr3[1:4,1:4] = 0
arr3[2:3,2:3] = 9
arr3

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 9, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

In [130]:
# another way of doing it, is by using the ones() function
output = np.ones((5,5), dtype='int32')
output

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [131]:
# now, we can create another array, for the inner part of the ones aray with 0's
z = np.zeros((3,3), dtype='int32')
# and finally, for that array, we can asssign "9" for the center number
z[1,1] = 9
z

array([[0, 0, 0],
       [0, 9, 0],
       [0, 0, 0]])

In [132]:
# Finally, we can assign "z" to the inner part of "ones"
output[1:4,1:4] = z
output

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 9, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

### Important

In [134]:
# when we copy arrays, and later on we change one of the values in the copied array, that value will be changed as well in the initial array,
# that was used for the copy.

In [152]:
a = np.array([1,2,3])
b = a.copy()       # b = a.copy()
b[0] = 100
print(b)  # b = [100 2 3]
print(a)  # a = [1 2 3]

[100   2   3]
[1 2 3]


In [144]:
# array "a" has the same value as b. When we said that b = a, and we set a different value for the item at index 0, we said that the variable "b",
# points to the same index for the variable "a". Therefore one changes the other
# in order to prevent that from happening, we need to use the copy() function

### Mathematics



In [154]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [156]:
a + 2 # we add 2 to each element

array([3, 4, 5, 6])

In [157]:
a - 2

array([-1,  0,  1,  2])

In [158]:
a * 2

array([2, 4, 6, 8])

In [159]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [160]:
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [161]:
# Take the sin, cos, tag, cotg
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

##### Linear Algebra

In [164]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

# wwe cannot directly multiple matrices if they are of different sizes, and that is why we use the matmul() function

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [165]:
# In Linear Algebra, the cols of the first matrix should be equal to the rows of the second matrix

In [167]:
# Find the Determinant
c = np.identity(3)
np.linalg.det(c)

1.0

In [168]:
## Reference docs (https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)

# Determinant
# Trace
# Singular Vector Decomposition
# eigenvalues
# Matrix Norm
# Inverse

##### Statistics

In [169]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [170]:
np.min(stats) # if we want to do it for every row, we can add "axis=1", and that way we get the "min" for every row

1

In [171]:
np.max(stats)

6

In [172]:
np.sum(stats) # sum all the elements in the matrix

21

In [173]:
np.sum(stats, axis=0) # this will sum all the elements for every column, going downwards

array([5, 7, 9])

##### ReOrganazing Arrays

In [177]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((4,2)) # or we can pass it as 2:2:2, as long as it has the same amout of values
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [180]:
# Vertically Stacking Vectors/Matrices
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2]) # or we can keep passing "v2" if we want more copies of the array in the new matrix

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8],
       [5, 6, 7, 8]])

In [182]:
# Horizontal Stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

print(h1)
print(h2)
print()
np.hstack((h1,h2))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0.]
 [0. 0.]]



array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

#### Miscellaneous

##### Load Data From File


In [193]:
filedata = np.genfromtxt('data.txt', delimiter=',') # we load data from file with the .genfromtxt()function 
filedata.astype('int32') # and further we can cast the float type ass integer with the .astype() function

array([[   1,    1,    2,    3,    4,   56,    1,  123,    4,   23,   56,
           7,    1,    3,    4,    5,    1],
       [1234,  236,    6, 1234,  213,   43,   52,  354,    1,   23,   66,
           6,   12,   14,   61,    1,    3],
       [ 123,  315,    6,    7,   43,  232, 4213,    6,    4,    3,   31,
          23,    3,    4,   61,    1,    3],
       [   7,    8,    9,    9,  456,    9,  564,  624,   58,    9,    2,
          34,   77,   42,    0,   61,    1]])

In [194]:
# the delimeter='' determines how the data is split

##### Boolean Masking and Advanced Indexing

In [195]:
filedata > 50 # we can check which items are greater than 50, and then return a True value if they are

array([[False, False, False, False, False,  True, False,  True, False,
        False,  True, False, False, False, False, False, False],
       [ True,  True, False,  True,  True, False,  True,  True, False,
        False,  True, False, False, False,  True, False, False],
       [ True,  True, False, False, False,  True,  True, False, False,
        False, False, False, False, False,  True, False, False],
       [False, False, False, False,  True, False,  True,  True,  True,
        False, False, False,  True, False, False,  True, False]])

In [196]:
filedata[filedata > 50] # that way we can index where it is greater than 50. We grab only the values

array([  56.,  123.,   56., 1234.,  236., 1234.,  213.,   52.,  354.,
         66.,   61.,  123.,  315.,  232., 4213.,   61.,  456.,  564.,
        624.,   58.,   77.,   61.])

In [198]:
# You can also index with a list in NumPy
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]

array([2, 3, 9])

In [200]:
# We can also see which of the values is greater than 50 only in the first row, by using the any() function
np.any(filedata > 50, axis=0)

array([ True,  True, False,  True,  True,  True,  True,  True,  True,
       False,  True, False,  True, False,  True,  True, False])

In [201]:
# or
((filedata > 50) & (filedata < 100))

array([[False, False, False, False, False,  True, False, False, False,
        False,  True, False, False, False, False, False, False],
       [False, False, False, False, False, False,  True, False, False,
        False,  True, False, False, False,  True, False, False],
       [False, False, False, False, False, False, False, False, False,
        False, False, False, False, False,  True, False, False],
       [False, False, False, False, False, False, False, False,  True,
        False, False, False,  True, False, False,  True, False]])

In [220]:
h1 = np.array((1,2,3,4,5))
h2 = np.array((6,7,8,9,10))
h3 = np.array((11,12,13,14,15))
h4 = np.array((16,17,18,19,20))
h5 = np.array((21,22,23,24,25))
h6 = np.array((26,27,28,29,30))

stack = np.vstack((h1,h2,h3,h4,h5,h6))
stack

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [251]:
stack[[0,4,5], 3:]  # left side is the index of the rows, and right side is from 3 until the last index for the columns

array([[ 4,  5],
       [24, 25],
       [29, 30]])

In [ ]:
cd 